import os
from pathlib import Path

MAX_EVALS = 2000

# pygad configuration parameters
PYGAD_POPULATION_SIZE = 100
PYGAD_NUM_GENERATIONS = MAX_EVALS // PYGAD_POPULATION_SIZE
PYGAD_MUTATION_PERCENT_GENES = 5
PYGAD_NUM_PARENTS_MATING = 20
PYGAD_KEEP_PARENTS = 2

# Parallel processing configuration
# Set to an integer to use a specific number of CPUs, or something else (like None) to use all.
NUM_PROCESSORS = None

#configuration file for sumo
# ``TLS_SUMOCFG`` / ``TLS_BASELINE_DATA`` let multi-instance runners point every
# process at a non-default instance. Spawned multiprocessing workers re-import
# this module, so reading them here (not just in the parent) keeps every worker
# on the same instance. Unset → the default Jakarta network.
CONFIG_FILE = os.environ.get(
    "TLS_SUMOCFG",
    os.path.join(os.path.dirname(__file__), "src/sumo_setup/osm.sumocfg"),
)
SUMO_ARGS = [
    "sumo", 
    "-c", CONFIG_FILE, 
    "--no-step-log",          
    "--no-warnings",          
    "--time-to-teleport", "-1", 
    "--duration-log.disable",
    "--duration-log.statistics", "false",   
]
BASELINE_TRAFFIC_DATA = os.environ.get(
    "TLS_BASELINE_DATA",
    os.path.join(os.path.dirname(__file__), "src/outputs/baseline_traffic_data.json"),
)
OUTPUT_JSON_PATH = os.path.join(os.path.dirname(__file__), "src/outputs/check_traffic_cycles.json")

# Custom Optimizer configuration
POPULATION_SIZE = 100
NUM_GENERATIONS = MAX_EVALS // POPULATION_SIZE
GAUSSIAN_NOISE = 0.10  # 10% Gaussian perturbation for baseline-perturbed init
NOVEL_MUTATION = False  # Enable or disable pair-cluster mutation

# Base random seed (used by distance-matrix plotting / reproducible runs).
SEED_BASE = 42

# Clustering thresholds
CLUSTER_THRESHOLD_FASTEST = 300
CLUSTER_THRESHOLD_SHORTEST = 4000
CLUSTER_THRESHOLD_EUCLIDIAN = 3500

# ── Linkage-tree distance strategies (single source of truth) ──────────
# Every linkage-based optimiser / analysis tool iterates over these. To add a
# new strategy (e.g. "manhattan"): add its name here AND a matching variant in
# src/plot/tls_distances.py (which generates tls_distances_<name>.json). All
# consumers that call src.novel.distance_trees.distance_tree_paths() then pick
# it up automatically.
TREE_STRATEGIES = ["shortest", "euclidian", "fastest", "random"]

# Custom Optimizer  Bounds and Mutation
# Per-type phase-duration floors (minimums within the fixed cycle). Green/red
# ceilings are no longer static: they come from the dynamic per-TLS
# phase_upper_bounds in fitness_evaluation.py.
GREEN_FLOOR  = 24.0   # green phase minimum
RED_FLOOR    = 5.0    # red phase minimum
# Yellow phases are frozen to a fixed band (both bounds still used to clamp).
YELLOW_FLOOR = 3.0
YELLOW_CEIL  = 6.0
MUTATION_RATE = 0.1

# SHADE pairwise step-mutation (cluster v3 crossover hook)
STEP_SIZE = 1.0                  # green-budget step: second TLS green = first + STEP_SIZE
SHADE_PAIRWISE_MUTATION = False  # enable step-pairwise-mutation in cluster v3 crossover

CYCLE_LENGTH = 90

# Only TLSs whose phase count is in this set are optimised. Other TLSs are
# filtered out at baseline-JSON generation time (see src/sumo_setup/generation.py)
# and keep whatever durations the SUMO network file holds during simulation.
OPTIMIZE_PHASE_COUNTS = {3, 4}

# ── Instances ──────────────────────────────────────────────────────────
# Per-instance SUMO config, baseline traffic data, and output directory.
# Multi-instance runners (e.g. src.experiments.baseline_experiments) switch
# instances by exporting TLS_SUMOCFG / TLS_BASELINE_DATA from these before each
# run.  Jakarta is the default the algorithm modules already target, so its
# files stay in src/outputs (out_dir == that folder); the others live under
# src/outputs/instances/<instance>/.  Each instance's baseline_traffic_data.json
# (the filtered current-SUMO config) is generated by
# best_config_instance_experiments and reused everywhere.
_ROOT = Path(__file__).resolve().parent
_OUTPUTS = _ROOT / "src" / "outputs"

INSTANCES = {
    "jakarta": {
        "sumocfg": _ROOT / "src" / "sumo_setup" / "osm.sumocfg",
        "baseline_data": _OUTPUTS / "baseline_traffic_data.json",
        "out_dir": _OUTPUTS,
    },
    "beijing": {
        "sumocfg": _ROOT / "src" / "sumo_setup_beijing" / "osm.sumocfg",
        "baseline_data": _OUTPUTS / "instances" / "beijing" / "baseline_traffic_data.json",
        "out_dir": _OUTPUTS / "instances" / "beijing",
    },
    "kotakinabalu": {
        "sumocfg": _ROOT / "src" / "sumo_setup_kotakinabalu" / "osm.sumocfg",
        "baseline_data": _OUTPUTS / "instances" / "kotakinabalu" / "baseline_traffic_data.json",
        "out_dir": _OUTPUTS / "instances" / "kotakinabalu",
    },
}