"""
DG2: A Faster and More Accurate Differential Grouping for Large-Scale Black-Box Optimization
Implementation based on:
    Omidvar et al. (2017), IEEE Transactions on Evolutionary Computation, Vol. 21, No. 6

Parallelisation strategy
------------------------
Every unique probe point generated by the ISM step is independent — DG2 only
needs them all *collected* before DSM can run.  We therefore:

  1. Compute f_base on the midpoint (1 call, unavoidable serial dependency).
  2. Submit ALL remaining unique probe points (the n single-perturbation points
     + the n(n-1)/2 double-perturbation points) to a ProcessPoolExecutor in one
     batch, using every available CPU core.
  3. Collect results and assemble Λ, F, f_hat exactly as Algorithm 2 requires.

This turns what was O(n²) sequential SUMO launches into a single parallel
wave, saturating all cores for the bulk of the work.

Usage in traffic light optimisation
------------------------------------
Run DG2 before the genetic algorithm to identify which phase-duration genes
interact with each other.  Interacting genes should be optimised together;
separable genes can be treated independently.

Phase duration constraints
--------------------------
Phase type is inferred from the dominant character in the state string:
  Green  (G dominant) : gene bounds [24, 85],  min after clamping = 24 s
  Yellow (y dominant) : gene bounds [ 3,  6],  clamped to [3, 6] — NOT adjusted
  Red    (r dominant) : gene bounds [ 5, 85],  min after clamping =  5 s

Cycle length = 90 s.  Any remainder or shortfall after clamping is
absorbed by the green-or-red phase with the smallest current duration.
"""

import json
import math
import os
import sys
import time
import numpy as np
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Callable

# Add project root to sys.path so config and other modules are importable
sys.path.append(str(Path(__file__).resolve().parent.parent.parent))


# ---------------------------------------------------------------------------
# Machine epsilon  (IEEE 754 double precision)
# ---------------------------------------------------------------------------
MACHINE_EPSILON = np.finfo(float).eps          # ≈ 2.220446e-16
GAMMA2 = 2 * MACHINE_EPSILON / (1 - 2 * MACHINE_EPSILON)   # γ₂  (Theorem S.2)

CYCLE_LENGTH = 90  # seconds

# Per-phase-type bounds and minima
PHASE_BOUNDS = {
    "green":  (24, 85),
    "yellow": ( 3,  6),
    "red":    ( 5, 85),
}


# ---------------------------------------------------------------------------
# Phase-type helper
# ---------------------------------------------------------------------------

def _phase_type(state: str) -> str:
    """
    Infer phase type from SUMO state string.

    Counts G/g (green), y (yellow), r/R (red) characters and returns the
    majority type.  Ties broken in priority order: green > yellow > red.

    Examples
    --------
    "GGGG"   -> "green"
    "yyyy"   -> "yellow"
    "rrrr"   -> "red"
    "GGrr"   -> "green"   (2 G vs 2 r — green wins tie)
    "rrGG"   -> "green"
    """
    s = state.lower()
    counts = {
        "green":  s.count("g"),
        "yellow": s.count("y"),
        "red":    s.count("r"),
    }
    # Priority order for ties: green > yellow > red
    for ptype in ("green", "yellow", "red"):
        if counts[ptype] == max(counts.values()):
            return ptype
    return "red"  # fallback (unreachable)


# ---------------------------------------------------------------------------
# Top-level worker — must be a plain module-level function so that
# ProcessPoolExecutor can pickle it across processes.
# ---------------------------------------------------------------------------

def _eval_probe(args):
    """
    Evaluate f at a single probe point.

    Parameters
    ----------
    args : (f, x, tag)
        f   — the fitness callable
        x   — the probe vector (numpy array)
        tag — an opaque identifier returned unchanged so the caller can
              route the result back to the right cell in F or f_hat.
              Convention:
                ("base",)        -> f_base
                ("single", i)   -> f_hat[i]
                ("double", i, j) -> F[i, j]

    Returns
    -------
    (tag, float)
    """
    f, x, tag = args
    return tag, float(f(x))


# ---------------------------------------------------------------------------
# Step 1 - Interaction Structure Matrix  (Algorithm 2, parallelised)
# ---------------------------------------------------------------------------

def _compute_ISM_parallel(
    f: Callable[[np.ndarray], float],
    n: int,
    x_lower: np.ndarray,
    x_upper: np.ndarray,
    n_workers: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, float, int]:
    """
    Build the raw Interaction Structure Matrix Lambda using parallel evaluation.

    All unique probe points are submitted in a single batch to a
    ProcessPoolExecutor.  The only serial step is the final assembly of Lambda
    from the collected results, which is pure numpy and negligible.

    Returns
    -------
    Lambda   : (n, n) raw |delta1 - delta2| values
    F        : (n, n) f(x with dims i and j both perturbed)
    f_hat    : (n,)   f(x with only dim i perturbed)
    f_base   : f at the mid-point
    evals    : total unique evaluations dispatched
    """
    m = 0.5 * (x_lower + x_upper)   # base point

    # Build the complete list of probe tasks up-front.
    # Each task is (f, point, tag).
    tasks = []

    # Base point
    tasks.append((f, m.copy(), ("base",)))

    # Single-perturbation points: perturb only dimension i
    for i in range(n):
        x = m.copy()
        x[i] = x_upper[i]
        tasks.append((f, x, ("single", i)))

    # Double-perturbation points: perturb dimensions i and j
    for i in range(n - 1):
        for j in range(i + 1, n):
            x = m.copy()
            x[i] = x_upper[i]
            x[j] = x_upper[j]
            tasks.append((f, x, ("double", i, j)))

    evals = len(tasks)   # = 1 + n + n(n-1)/2  ==  n(n+1)/2 + 1  (lower bound)

    # Dispatch all tasks in parallel
    f_base = np.nan
    f_hat  = np.full(n, np.nan)
    F      = np.full((n, n), np.nan)

    with ProcessPoolExecutor(max_workers=n_workers) as pool:
        futures = {pool.submit(_eval_probe, task): task[2] for task in tasks}
        for future in as_completed(futures):
            tag, value = future.result()
            if tag[0] == "base":
                f_base = value
            elif tag[0] == "single":
                f_hat[tag[1]] = value
            else:  # "double"
                i, j = tag[1], tag[2]
                F[i, j] = value

    # Assemble Lambda — pure numpy, no more f calls
    Lambda = np.zeros((n, n))
    for i in range(n - 1):
        delta1_i = f_hat[i] - f_base          # delta1 at xj = mj
        for j in range(i + 1, n):
            delta2_i = F[i, j] - f_hat[j]    # delta2 at xj = upper
            lam = abs(delta1_i - delta2_i)
            Lambda[i, j] = lam
            Lambda[j, i] = lam               # symmetric

    return Lambda, F, f_hat, f_base, evals


# ---------------------------------------------------------------------------
# Step 2 - Design Structure Matrix  (Algorithm 3, unchanged from paper)
# ---------------------------------------------------------------------------

def _compute_DSM(
    Lambda: np.ndarray,
    F: np.ndarray,
    f_hat: np.ndarray,
    f_base: float,
    n: int,
) -> np.ndarray:
    """
    Convert the raw ISM (Lambda) into a binary Design Structure Matrix (Theta).

    Uses per-pair roundoff bounds einf and esup (Equations 3-7 in the paper)
    so the threshold epsilon is parameter-free and adapts to each pair of variables.

    Returns
    -------
    Theta : (n, n) int array;  Theta_ij = 1  means xi and xj interact.
    """
    gamma_sqrt_n = MACHINE_EPSILON * math.sqrt(n) / (1 - math.sqrt(n) * MACHINE_EPSILON)

    Theta = np.full((n, n), np.nan)
    eta0 = 0   # pairs reliably separable  (lam < einf)
    eta1 = 0   # pairs reliably interacting (lam > esup)

    # First pass: assign clear-cut 0s and 1s
    for i in range(n - 1):
        for j in range(i + 1, n):
            fij = float(F[i, j]) if not np.isnan(F[i, j]) else 0.0
            fi  = float(f_hat[i]) if not np.isnan(f_hat[i]) else 0.0
            fj  = float(f_hat[j]) if not np.isnan(f_hat[j]) else 0.0
            fb  = float(f_base)

            einf = GAMMA2 * max(abs(fb) + abs(fij), abs(fi) + abs(fj))
            esup = gamma_sqrt_n * max(abs(fb), abs(fij), abs(fi), abs(fj))
            lam  = Lambda[i, j]

            if lam < einf:
                Theta[i, j] = Theta[j, i] = 0
                eta0 += 1
            elif lam > esup:
                Theta[i, j] = Theta[j, i] = 1
                eta1 += 1
            # else: ambiguous — handled in second pass

    # Second pass: threshold ambiguous values with Equation (7)
    total_reliable = eta0 + eta1
    for i in range(n - 1):
        for j in range(i + 1, n):
            if not np.isnan(Theta[i, j]):
                continue

            fij = float(F[i, j]) if not np.isnan(F[i, j]) else 0.0
            fi  = float(f_hat[i]) if not np.isnan(f_hat[i]) else 0.0
            fj  = float(f_hat[j]) if not np.isnan(f_hat[j]) else 0.0
            fb  = float(f_base)

            einf = GAMMA2 * max(abs(fb) + abs(fij), abs(fi) + abs(fj))
            esup = gamma_sqrt_n * max(abs(fb), abs(fij), abs(fi), abs(fj))

            if total_reliable == 0:
                epsilon = 0.5 * (einf + esup)
            else:
                epsilon = (eta0 / total_reliable) * einf + (eta1 / total_reliable) * esup

            Theta[i, j] = Theta[j, i] = 1 if Lambda[i, j] > epsilon else 0

    np.fill_diagonal(Theta, 0)
    Theta = np.nan_to_num(Theta, nan=0.0)
    return Theta.astype(int)


# ---------------------------------------------------------------------------
# Step 3 - Connected Components  (BFS, linear in n)
# ---------------------------------------------------------------------------

def _connected_components(Theta: np.ndarray, n: int) -> tuple[list[list[int]], list[int]]:
    """
    Partition variables into nonseparable groups and fully separable singletons.

    Returns
    -------
    groups    : list of sorted lists of interacting gene indices
    separable : sorted list of singleton (separable) gene indices
    """
    visited = [False] * n
    groups, separable = [], []

    for start in range(n):
        if visited[start]:
            continue
        component, queue = [], [start]
        visited[start] = True
        while queue:
            node = queue.pop(0)
            component.append(node)
            for nb in range(n):
                if not visited[nb] and Theta[node, nb] == 1:
                    visited[nb] = True
                    queue.append(nb)

        if len(component) == 1:
            separable.append(component[0])
        else:
            groups.append(sorted(component))

    return groups, separable


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_dg2(
    f: Callable[[np.ndarray], float],
    n: int,
    x_lower: np.ndarray,
    x_upper: np.ndarray,
    gene_labels: list[str] | None = None,
    output_path: str | Path = "dg2_results.json",
    n_workers: int | None = None,
    verbose: bool = True,
) -> dict:
    """
    Run the parallel DG2 algorithm to detect variable interactions.

    Parameters
    ----------
    f           : Black-box fitness function f(x) -> float.
                  IMPORTANT: must be picklable (i.e. a module-level function
                  or a class with __call__).  Use build_traffic_fitness_wrapper()
                  which returns the picklable TrafficFitnessWrapper class.
    n           : Number of decision variables (genes).
    x_lower     : Lower bounds array, shape (n,).
    x_upper     : Upper bounds array, shape (n,).
    gene_labels : Human-readable name for each gene.  Defaults to "gene_i".
    output_path : Destination for the JSON results file.
    n_workers   : Number of parallel worker processes.
                  Defaults to os.cpu_count() — uses every available core.
    verbose     : Print progress to stdout.

    Returns
    -------
    results dict with keys:
        groups                  — interacting groups (list of dicts)
        separable_genes         — fully separable genes (list of dicts)
        interaction_matrix      — n x n binary adjacency matrix
        lambda_matrix           — n x n raw |delta1 - delta2| values
        gene_labels             — gene name strings
        n_genes / n_groups / n_separable
        function_evaluations    — total f calls (= n(n+1)/2 + 1, the lower bound)
        n_workers_used          — actual worker count
        computation_time_seconds
        timestamp
    """
    if gene_labels is None:
        gene_labels = [f"gene_{i}" for i in range(n)]

    if n_workers is None:
        n_workers = os.cpu_count() or 1

    x_lower = np.asarray(x_lower, dtype=float)
    x_upper = np.asarray(x_upper, dtype=float)

    lower_bound_evals = n * (n + 1) // 2 + 1

    if verbose:
        print(f"[DG2] Starting parallel interaction detection")
        print(f"[DG2]   Genes          : {n}")
        print(f"[DG2]   Workers        : {n_workers} / {os.cpu_count()} available cores")
        print(f"[DG2]   Probe points   : {lower_bound_evals}  (theoretical lower bound)")

    t_start = time.perf_counter()

    # Step 1 — parallel ISM
    if verbose:
        print("[DG2] Step 1/3 — Dispatching all probe evaluations in parallel ...")
    Lambda, F, f_hat, f_base, evals = _compute_ISM_parallel(f, n, x_lower, x_upper, n_workers)

    # Step 2 — DSM (fast numpy, no f calls)
    if verbose:
        print("[DG2] Step 2/3 — Computing Design Structure Matrix (DSM) ...")
    Theta = _compute_DSM(Lambda, F, f_hat, f_base, n)

    # Step 3 — connected components (BFS)
    if verbose:
        print("[DG2] Step 3/3 — Extracting connected components ...")
    groups, separable = _connected_components(Theta, n)

    elapsed = time.perf_counter() - t_start

    # Human-readable output
    named_groups = [
        {
            "group_id": gid,
            "size": len(grp),
            "gene_indices": grp,
            "gene_labels": [gene_labels[i] for i in grp],
        }
        for gid, grp in enumerate(groups)
    ]
    named_separable = [
        {"gene_index": i, "gene_label": gene_labels[i]} for i in separable
    ]

    if verbose:
        print(f"\n[DG2] Results -----------------------------------------------")
        print(f"[DG2]   Total genes          : {n}")
        print(f"[DG2]   Workers used         : {n_workers}")
        print(f"[DG2]   Nonseparable groups  : {len(groups)}")
        print(f"[DG2]   Separable genes      : {len(separable)}")
        print(f"[DG2]   Function evaluations : {evals}  (lower bound = {lower_bound_evals})")
        print(f"[DG2]   Computation time     : {elapsed:.4f} s")
        print(f"[DG2] -----------------------------------------------------------")
        for g in named_groups:
            print(f"[DG2]   Group {g['group_id']} (size {g['size']}): {g['gene_labels']}")
        if named_separable:
            print(f"[DG2]   Separable : {[s['gene_label'] for s in named_separable]}")

    results = {
        "groups": named_groups,
        "separable_genes": named_separable,
        "interaction_matrix": Theta.tolist(),
        "lambda_matrix": Lambda.tolist(),
        "gene_labels": gene_labels,
        "n_genes": n,
        "n_groups": len(groups),
        "n_separable": len(separable),
        "function_evaluations": evals,
        "n_workers_used": n_workers,
        "computation_time_seconds": round(elapsed, 6),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as fh:
        json.dump(results, fh, indent=4)

    if verbose:
        print(f"[DG2] Results saved -> {output_path}")

    return results


# ---------------------------------------------------------------------------
# Traffic-light integration helper
# ---------------------------------------------------------------------------

class TrafficFitnessWrapper:
    """
    Picklable wrapper around your traffic fitness function.

    Phase duration constraints (applied per TLS per call):
      - Green  (state dominant 'G'): minimum 24 s, bounds [24, 85]
      - Yellow (state dominant 'y'): clamped to [3, 6] s — NOT adjusted for remainder
      - Red    (state dominant 'r'): minimum  5 s, bounds [5, 85]

    After clamping all phases to their type bounds, the difference from the
    90 s cycle target is absorbed by the green-or-red phase with the smallest
    current duration (yellow phases are never touched in this step).

    A plain closure (lambda or def inside a function) is NOT picklable and
    cannot cross process boundaries.  A class with __call__ IS picklable as
    long as all its attributes are also picklable.
    """

    def __init__(self, fitness_function, tls_mapping):
        self.fitness_function = fitness_function
        self.tls_mapping      = tls_mapping

    def __call__(self, vector: np.ndarray) -> float:
        tls_durations = {}

        for tls in self.tls_mapping:
            tls_id      = tls["tls_id"]
            phase_types = tls["phase_types"]   # list of "green"/"yellow"/"red"
            raw         = list(vector[tls["start_idx"]: tls["end_idx"]])
            n_phases    = len(raw)

            # ----------------------------------------------------------------
            # Step 1 — clamp each gene to its per-type bounds
            # ----------------------------------------------------------------
            durations = []
            for raw_val, ptype in zip(raw, phase_types):
                lo, hi = PHASE_BOUNDS[ptype]
                durations.append(int(round(max(lo, min(hi, raw_val)))))

            # ----------------------------------------------------------------
            # Step 2 — adjust for cycle-length target (90 s)
            #
            # Yellow phases are fixed after clamping — only green and red
            # absorb the remainder.  We find the green-or-red phase with the
            # smallest current duration and add/subtract there.
            # ----------------------------------------------------------------
            remainder = CYCLE_LENGTH - sum(durations)

            if remainder != 0:
                # Indices of adjustable (green or red) phases
                adjustable = [
                    i for i, ptype in enumerate(phase_types)
                    if ptype in ("green", "red")
                ]

                if adjustable:
                    # Pick the adjustable phase with the smallest current duration
                    target_idx = min(adjustable, key=lambda i: durations[i])
                    durations[target_idx] += remainder

                    # Safety: enforce minimum even after adjustment
                    lo, _ = PHASE_BOUNDS[phase_types[target_idx]]
                    if durations[target_idx] < lo:
                        # Distribute the minimum-violation back to the largest
                        # adjustable phase to avoid an infeasible solution
                        durations[target_idx] = lo
                        fallback = max(adjustable, key=lambda i: durations[i])
                        durations[fallback] += CYCLE_LENGTH - sum(durations)

            tls_durations[tls_id] = durations

        return self.fitness_function(tls_durations)


def build_traffic_fitness_wrapper(
    baseline_data: dict,
    fitness_function: Callable[[dict], float],
) -> tuple[Callable[[np.ndarray], float], int, np.ndarray, np.ndarray, list[str]]:
    """
    Build a picklable fitness wrapper compatible with multiprocessing.

    Derives the TLS mapping (including per-phase type from the state string)
    directly from *baseline_data*, so the caller only needs to supply the
    loaded JSON.

    Gene bounds are set per phase type:
      green  -> [24, 85]
      yellow -> [ 3,  6]
      red    -> [ 5, 85]

    Returns
    -------
    f        : TrafficFitnessWrapper instance (picklable, safe for DG2 workers)
    n        : number of genes
    x_lower  : lower bounds per gene (type-aware)
    x_upper  : upper bounds per gene (type-aware, all 85 except yellow capped at 6)
    labels   : gene names, e.g. ["186797066_phase_1", "186797066_phase_2", ...]
    """
    tls_mapping = []
    gene_idx    = 0
    x_lower_list: list[float] = []
    x_upper_list: list[float] = []
    labels:       list[str]   = []

    for tls_id in sorted(baseline_data["tls_data"].keys()):
        phase_keys  = sorted(baseline_data["tls_data"][tls_id].keys())
        phase_types = []

        for pk in phase_keys:
            state = baseline_data["tls_data"][tls_id][pk].get("state", "")
            ptype = _phase_type(state)
            phase_types.append(ptype)

            lo, hi = PHASE_BOUNDS[ptype]
            x_lower_list.append(float(lo))
            x_upper_list.append(float(hi))
            labels.append(f"{tls_id}_{pk}")

        tls_mapping.append({
            "tls_id":      tls_id,
            "num_phases":  len(phase_keys),
            "phase_types": phase_types,
            "start_idx":   gene_idx,
            "end_idx":     gene_idx + len(phase_keys),
        })
        gene_idx += len(phase_keys)

    n       = gene_idx
    x_lower = np.array(x_lower_list, dtype=float)
    x_upper = np.array(x_upper_list, dtype=float)

    f = TrafficFitnessWrapper(fitness_function, tls_mapping)
    return f, n, x_lower, x_upper, labels


# ---------------------------------------------------------------------------
# Quick self-test / standalone demo
# The test function must be at module level to be picklable by workers.
# ---------------------------------------------------------------------------

def _toy_f(x: np.ndarray) -> float:
    """f(x) = (x0+x1)^2 + x2^2 + x3^2 + (x4+x5+x6)^2
    Expected groups: {0,1}, {4,5,6}   separable: {2}, {3}
    """
    return (x[0] + x[1])**2 + x[2]**2 + x[3]**2 + (x[4] + x[5] + x[6])**2


if __name__ == "__main__":
    from config import BASELINE_TRAFFIC_DATA
    from src.genetic_algorithm.fitness_evaluation import fitness_function as _traffic_fitness

    print("=" * 60)
    print("DG2 — interaction detection on real baseline traffic data")
    print("=" * 60)

    # Load the real baseline data (same pattern as the other optimizers)
    with open(BASELINE_TRAFFIC_DATA, "r") as _fh:
        baseline_data = json.load(_fh)

    # Build the wrapper — tls_mapping is derived from baseline_data internally
    f, n, x_lower, x_upper, labels = build_traffic_fitness_wrapper(
        baseline_data    = baseline_data,
        fitness_function = _traffic_fitness,
    )

    results = run_dg2(
        f           = f,
        n           = n,
        x_lower     = x_lower,
        x_upper     = x_upper,
        gene_labels = labels,
        output_path = "src/outputs/dg2_results.json",
        verbose     = True,
    )

    print("\nSaved results preview:")
    print(f"  Groups    : {[g['gene_labels'] for g in results['groups']]}")
    print(f"  Separable : {[s['gene_label'] for s in results['separable_genes']]}")
    print(f"  Workers   : {results['n_workers_used']}")